config/routes.rb
Wedding::Application.routes.draw do
  resources :guest_groups

    root :to => 'wedding#index'

end

app/models/guest_group.rb
class GuestGroup < ActiveRecord::Base
  attr_accessible :email, :full_name, :kids, :plus_one, :vulnerabilities
  validates_uniqueness_of :email, :message => "You already told us you were coming!"
  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/guest_groups_controller.rb
class GuestGroupsController < ApplicationController

  def create
    @guest_group = GuestGroup.new(params[:guest_group])

    respond_to do |format|
      if @guest_group.save
        format.html { redirect_to root_url, notice: 'Thank You for Your RSVP! See You in October!' }
        format.json { render json: @guest_group, status: :created, location: @guest_group }
      else
        format.html { render "wedding/index" }
        format.json { render json: @guest_group.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/wedding_controller.rb
class WeddingController < ApplicationController
  protect_from_forgery
  def index
    @guest_group = GuestGroup.new
    #@guest_group.vulnerabilities = "Examples: Silver Bullets, Garlic, CO2, Red Meat, Carrots."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guest_groups_helper.rb
module GuestGroupsHelper
end

app/views/guest_groups/_form.html.haml
%h1.overview.copy.line-5.blood R.S.V.P.
.rsvp_form
  = form_for @guest_group do |f|
    - if @guest_group.errors.any?
      #error_explanation
        %h2= "#{pluralize(@guest_group.errors.count, "error")} prohibited this RSVP from being saved:"
        %ul
          - @guest_group.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label :full_name
      = f.text_field :full_name
    .field
      = f.label :email
      = f.text_field :email
    .field
      = f.label :kids
      = f.number_field :kids
    .checkbox
      = f.label :plus_one
      = f.check_box :plus_one
    .textarea
      = f.label :vulnerabilities
      = f.text_area :vulnerabilities, :value => 'Examples: Silver Bullets, Garlic, CO2, Red Meat, Carrots.', :id => 'vul', :style => 'color:#C9C9C9'
    .actions
      = f.submit 'Submit RSVP'
.save_the_date
  = image_tag 'save_the_date.png'

app/views/guest_groups/edit.html.haml
%h1 Editing guest_group

= render 'form'

= link_to 'Show', @guest_group
\|
= link_to 'Back', guest_groups_path

app/views/guest_groups/index.html.haml
%h1 Listing guest_groups

%table
  %tr
    %th Full name
    %th Email
    %th Kids
    %th Plus one
    %th
    %th
    %th

  - @guest_groups.each do |guest_group|
    %tr
      %td= guest_group.full_name
      %td= guest_group.email
      %td= guest_group.kids
      %td= guest_group.plus_one
      %td= link_to 'Show', guest_group
      %td= link_to 'Edit', edit_guest_group_path(guest_group)
      %td= link_to 'Destroy', guest_group, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Guest group', new_guest_group_path

app/views/guest_groups/new.html.haml
%h1 New guest_group

= render 'form'

= link_to 'Back', guest_groups_path

app/views/guest_groups/show.html.haml
%p#notice= notice

%p
  %b Full name:
  = @guest_group.full_name
%p
  %b Email:
  = @guest_group.email
%p
  %b Kids:
  = @guest_group.kids
%p
  %b Plus one:
  = @guest_group.plus_one

= link_to 'Edit', edit_guest_group_path(@guest_group)
\|
= link_to 'Back', guest_groups_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wedding</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>

<%= yield %>

</body>
</html>

app/views/wedding/_overview.haml
%section.overview.animation.row
  %h2.overview.copy.line-1 Adam&#8217;s and Ren&eacute;e&#8217;s
  %h2.overview.copy.line-2 Big
  %h2.overview.copy.line-3 White
  %h2.overview.copy.line-4 Wedding
  %h1.overview.copy.line-5.blood Of Terror
  %time.overview.copy 5:00PM Sunday
  %time.overview.copy October 13th 2013
  %address.overview.copy Timberline Lodge in Oregon

app/views/wedding/_what.haml
%section.what.row
  %div.what.copy
    %h1.what The Wedding and Party

    %h2.what The Ceremony
    %p.what We will be saying our vows at 7:00PM.

    %h2.what The Dress Code
    %p.what Cas&shy;u&shy;al or Awe&shy;some Mon&shy;ster Cos&shy;tumes. But be warned, if you come as a su&shy;per&shy;hero, you will leave as a zom&shy;bie.

    %h2.what The Party
    %p.what We will have heavy hors d&#8217;oeuvres, in&shy;cred&shy;ible Holmes Har&shy;bor Cel&shy;lars wines and de&shy;light&shy;ful Bruch&shy;lad&shy;dich Is&shy;lay single malt Scotch whis&shy;key (as well as less&shy;er spir&shy;its for our more fer&shy;al mon&shy;ster friends).
    %p.what And for our north&shy;west&shy;ern guests, we will have Mt. Hood Brew&shy;ery ales.
  %div.what.block
    %h1.what The Room Block
    %p.what 
      Call Timberline: 800.547.1406 or 503.272.3410 
      %br
      Reserve for the Hendricksen Wedding 
      %br
      %a{:href => 'http://www.timberlinelodge.com/contact/'}
        Timberline Lodge
  %div.what.block
    %h1.what The Gift Registry
    %p.what 
      We setup a Wanderable site
      %br
      for our honeymoon skiing in Japan!
      %br
      %a{:href => 'https://www.wanderable.com/hm/bigwhiteweddingofterror'}
        Online Registry

app/views/wedding/_where.haml
%section.where.row
  %h1.where.copy The Sinister Timberline Lodge
  %p.where.copy Tim&shy;ber&shy;line Lodge was con&shy;struc&shy;ted by hand with an army of starving and des&shy;per&shy;ate WPA work&shy;ers dur&shy;ing the Great De&shy;pres&shy;sion. Its rus&shy;tic style and warm halls be&shy;lie the sin&shy;is&shy;ter his&shy;tory of this lodge. Many ghosts have been spot&shy;ted out&shy;side the first aid room, where count&shy;less un&shy;for&shy;tu&shy;nate ski&shy;ers and moun&shy;tain&shy;eers have lost their lives over the long years. It is un&shy;known how many venge&shy;ful climb&shy;ing wights roam the up&shy;per moun&shy;tain, seek&shy;ing to de&shy;vour the breath and warmth of any who dare tres&shy;pass above the tree-line. Tim&shy;ber&shy;line Lodge stands on this threshold, astride the gulf between the liv&shy;ing and the dead.
   
  %p.where.copy The high&shy;way lead&shy;ing up the moun&shy;tain to&shy;wards the lodge was blas&shy;ted out of a ridge-line con&shy;tain&shy;ing an Nat&shy;ive Amer&shy;ic&shy;an Buri&shy;al Ground. To this day, su&shy;per&shy;sti&shy;tious loc&shy;als refer to the pass as the Si&shy;lent Rocks, and re&shy;fuse to speak while driv&shy;ing through that sec&shy;tion. Many un&shy;wary trav&shy;el&shy;ers have lost their lives on these twist&shy;ing moun&shy;tain roads, al&shy;though who is to say wheth&shy;er it was the ice <em>or something else</em> from bey&shy;ond the nat&shy;ur&shy;al world.
   
  %p.where.copy Tim&shy;ber&shy;line Lodge was fea&shy;tured in Kubrik&#8217;s clas&shy;sic Hor&shy;ror film The Shin&shy;ing. Do not fear though, can&shy;ni&shy;bal&shy;ist&shy;ic pi&shy;on&shy;eer spir&shy;its are thought by main&shy;stream his&shy;tor&shy;i&shy;ans to be en&shy;tirely fic&shy;tion&shy;al.

app/views/wedding/_wolf_like_me.haml
%section.wolf_like_me
  %h1 Our Song
  %h2 "Wolf Like Me" by TV on the Radio
  .lyrics.left
    %iframe{:allowfullscreen => "", :frameborder => "0", :src => "http://www.youtube.com/embed/j1-xRk6llh4"}
    %p.lyric.stanza Say say my playmate
    %p.lyric wont you lay hands on me
    %p.lyric mirror my malady
    %p.lyric transfer my tragedy

    %p.lyric.stanza Got a curse I cannot lift
    %p.lyric shines when the sunset shifts
    %p.lyric when the moon is round and full
    %p.lyric gotta bust that box gotta gut that fish

    %p.lyric.stanza My mind's aflame

  .lyrics.center
    %p.lyric We could jet in a stolen car
    %p.lyric but I bet we wouldn't get too far
    %p.lyric before the transformation takes
    %p.lyric and bloodlust tanks and
    %p.lyric crave gets slaked

    %p.lyric.stanza My mind has changed
    %p.lyric my body's frame but god I like it
    %p.lyric my hearts aflame
    %p.lyric my body's strained but god I like it

    %p.lyric.stanza My mind has changed
    %p.lyric my body's frame but god I like it
    %p.lyric my hearts aflame
    %p.lyric my body's strained but god I like it

    %p.lyric.stanza Charge me your day rate
    %p.lyric ill turn you out in kind
    %p.lyric when the moon is round and full
    %p.lyric gonna teach you tricks that'll blow your mongrel mind
    
    %p.lyric.stanza baby doll I recognize
    %p.lyric you're a hideous thing inside
    %p.lyric if ever there were a lucky kind it's
    %p.lyric you you you you

    %p.lyric.stanza I know its strange another way to get to know you
    %p.lyric you'll never know unless we go so let me show you
    %p.lyric I know its strange another way to get to know you
    %p.lyric we've got till noon here comes the moon
    %p.lyric so let it show you
    %p.lyric show you now

  .lyrics.right
    %p.lyric Dream me oh dreamer
    %p.lyric down to the floor
    %p.lyric open my hands and let them
    %p.lyric weave onto yours

    %p.lyric.stanza Feel me, completer
    %p.lyric down to my core
    %p.lyric open my heart and let it
    %p.lyric bleed onto yours

    %p.lyric.stanza Feeding on fever
    %p.lyric down all fours
    %p.lyric show you what all that
    %p.lyric howl is for

    %p.lyric.stanza Hey hey my playmate
    %p.lyric let me lay waste to thee
    %p.lyric burned down their hanging trees
    %p.lyric it's hot here hot here hot here hot here

    %p.lyric.stanza Got a curse we cannot lift
    %p.lyric shines when the sunset shifts
    %p.lyric there's a cure comes with a kiss
    %p.lyric the bite that binds the gift that gives

    %p.lyric.stanza now that we got gone for good
    %p.lyric writhing under your riding hood
    %p.lyric tell your gra'ma and your mama too
    %p.lyric it's true
    %p.lyric we're howling forever

app/views/wedding/index.haml
= render 'wedding/overview'
%section.rsvp.row
  = render 'guest_groups/form', guest_group: @guest_group
= render 'wedding/what'
= render 'wedding/where'
= render 'wedding/wolf_like_me'